name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Pin to a specific runner for consistency
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use latest checkout version

    - name: Install SSH dependencies
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0  # Use latest version
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Debug SSH Key
      if: failure()  # Run only if previous steps fail
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.txt
        head -n 5 key.txt
        ssh-keygen -y -P "" -f key.txt || echo "Failed to read key"

    - name: Add EC2 to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -o ConnectTimeout=10 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

    - name: Deploy to EC2
      run: |
        ssh -o ConnectTimeout=10 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          set -e
          cd ~/xenon-api
          git fetch origin
          git reset --hard origin/main
          export PATH=$PATH:/usr/local/bin  # Ensure npm and pm2 are in PATH
          npm ci --omit=dev
          pm2 restart my-app || pm2 start server.js --name my-app
          pm2 save
        '